"""Added category table

Revision ID: 7ce69930a77c
Revises: a23b73cbe790
Create Date: 2023-06-22 21:40:36.281144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce69930a77c'
down_revision = 'a23b73cbe790'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('expense', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('expense', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'expense', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.alter_column('expense', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('expense', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
